[package]
name = "working-samples"
version = "0.1.0"
authors = ["Jason Kim <dialogbox@gmail.com>"]

[dependencies]
hyper = "0.12.9"
hyper-tls = "0.3.0"
tokio = "0.1.8"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"
failure = "0.1.2"